# Generated by Django 4.1.5 on 2023-01-20 19:54

from django.db import migrations, models
import django.db.models.deletion
import voting_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=10, validators=[voting_app.models.pan_validator])),
                ('party', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.election')),
            ],
        ),
    ]
