# Generated by Django 4.1.5 on 2023-01-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_rename_candidate_closedcandidate_opencandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Election',
            new_name='ClosedElection',
        ),
        migrations.RemoveField(
            model_name='closedcandidate',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='opencandidate',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='opencandidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.openelection'),
        ),
    ]
